# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sci-rogue.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ap_rogue_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sci-rogue.proto',
  package='',
  serialized_pb=_b('\n\x0fsci-rogue.proto\x1a\x0e\x61p_rogue.proto\"]\n\x0fSciRogueMessage\x12\x1e\n\x07\x61pRogue\x18\x01 \x01(\x0b\x32\r.RogueAPStats\x12*\n\rroguePolicies\x18\x02 \x03(\x0b\x32\x13.RoguePolicyMessage\"Z\n\x12RoguePolicyMessage\x12\x10\n\x08rogueMac\x18\x01 \x01(\t\x12\x12\n\npolicyName\x18\x02 \x01(\t\x12\x10\n\x08ruleName\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\tB%\n#com.ruckuswireless.scg.protobuf.sci')
  ,
  dependencies=[ap_rogue_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SCIROGUEMESSAGE = _descriptor.Descriptor(
  name='SciRogueMessage',
  full_name='SciRogueMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='apRogue', full_name='SciRogueMessage.apRogue', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='roguePolicies', full_name='SciRogueMessage.roguePolicies', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=128,
)


_ROGUEPOLICYMESSAGE = _descriptor.Descriptor(
  name='RoguePolicyMessage',
  full_name='RoguePolicyMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rogueMac', full_name='RoguePolicyMessage.rogueMac', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='policyName', full_name='RoguePolicyMessage.policyName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ruleName', full_name='RoguePolicyMessage.ruleName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='RoguePolicyMessage.type', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=220,
)

_SCIROGUEMESSAGE.fields_by_name['apRogue'].message_type = ap_rogue_pb2._ROGUEAPSTATS
_SCIROGUEMESSAGE.fields_by_name['roguePolicies'].message_type = _ROGUEPOLICYMESSAGE
DESCRIPTOR.message_types_by_name['SciRogueMessage'] = _SCIROGUEMESSAGE
DESCRIPTOR.message_types_by_name['RoguePolicyMessage'] = _ROGUEPOLICYMESSAGE

SciRogueMessage = _reflection.GeneratedProtocolMessageType('SciRogueMessage', (_message.Message,), dict(
  DESCRIPTOR = _SCIROGUEMESSAGE,
  __module__ = 'sci_rogue_pb2'
  # @@protoc_insertion_point(class_scope:SciRogueMessage)
  ))
_sym_db.RegisterMessage(SciRogueMessage)

RoguePolicyMessage = _reflection.GeneratedProtocolMessageType('RoguePolicyMessage', (_message.Message,), dict(
  DESCRIPTOR = _ROGUEPOLICYMESSAGE,
  __module__ = 'sci_rogue_pb2'
  # @@protoc_insertion_point(class_scope:RoguePolicyMessage)
  ))
_sym_db.RegisterMessage(RoguePolicyMessage)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n#com.ruckuswireless.scg.protobuf.sci'))
# @@protoc_insertion_point(module_scope)
